services:
  - type: web
    name: timo-md
    env: node
    branch: main
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: PORT
        value: 3000
    autoDeploy: true
